from __future__ import annotations

from utils.sop_uplift.diagram_model import DiagramModel
from utils.sop_uplift.diagram_exporters.svg_exporter import export_svg


def export_diagram_pdf(model: DiagramModel) -> bytes:
    svg = export_svg(model).encode("utf-8")
    try:
        import cairosvg

        return cairosvg.svg2pdf(bytestring=svg)
    except Exception:
        # Fallback keeps local tests usable when Cairo system libraries are not available.
        from io import BytesIO
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import landscape, letter
        from reportlab.pdfgen import canvas

        buffer = BytesIO()
        page_size = landscape(letter)
        c = canvas.Canvas(buffer, pagesize=page_size)
        width, height = page_size
        c.setTitle(model.title)
        c.setFillColor(colors.HexColor("#0C233C"))
        c.setFont("Helvetica-Bold", 18)
        c.drawString(36, height - 42, model.title)
        c.setFont("Helvetica", 10)
        c.drawString(36, height - 60, f"{model.case_title} | {model.process_name}")
        c.setFillColor(colors.HexColor("#64748B"))
        c.drawString(36, 30, "Generated by TRACE SOP Uplift")
        c.showPage()
        c.save()
        return buffer.getvalue()
