from __future__ import annotations

import html

from utils.sop_uplift.diagram_model import DiagramModel


def export_svg(model: DiagramModel) -> str:
    lanes = sorted(model.lanes, key=lambda lane: lane.order)
    lane_height = 120
    width = 1100
    height = max(260, 120 + lane_height * max(1, len(lanes)))
    lane_lookup = {lane.lane_id: idx for idx, lane in enumerate(lanes)}
    node_positions: dict[str, tuple[int, int]] = {}
    lane_node_counts: dict[str, int] = {}

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#F8FAFD"/>',
        f'<text x="32" y="36" font-family="Arial" font-size="22" font-weight="700" fill="#0C233C">{html.escape(model.title)}</text>',
        f'<text x="32" y="60" font-family="Arial" font-size="12" fill="#4B5563">{html.escape(model.case_title)} | {html.escape(model.process_name)}</text>',
    ]

    for idx, lane in enumerate(lanes):
        y = 86 + idx * lane_height
        parts.append(f'<rect x="24" y="{y}" width="{width - 48}" height="{lane_height - 8}" fill="#FFFFFF" stroke="#DDE5F2"/>')
        parts.append(f'<rect x="24" y="{y}" width="150" height="{lane_height - 8}" fill="#0C233C"/>')
        parts.append(f'<text x="40" y="{y + 58}" font-family="Arial" font-size="13" font-weight="700" fill="#FFFFFF">{html.escape(lane.name)}</text>')

    for node in model.nodes:
        lane_idx = lane_lookup.get(node.lane_id, 0)
        count = lane_node_counts.get(node.lane_id, 0)
        lane_node_counts[node.lane_id] = count + 1
        x = 205 + count * 190
        y = 115 + lane_idx * lane_height
        node_positions[node.node_id] = (x, y)
        color = {
            "control": "#1E49E2",
            "risk": "#C00000",
            "evidence": "#EAAA00",
            "decision": "#00B8F5",
        }.get(node.type, "#FFFFFF")
        text_color = "#FFFFFF" if node.type in {"control", "risk"} else "#0C233C"
        parts.append(f'<rect x="{x}" y="{y}" width="145" height="52" rx="6" fill="{color}" stroke="#94A3B8"/>')
        parts.append(f'<text x="{x + 12}" y="{y + 29}" font-family="Arial" font-size="12" fill="{text_color}">{html.escape(node.label[:22])}</text>')

    for edge in model.edges:
        start = node_positions.get(edge.from_node_id)
        end = node_positions.get(edge.to_node_id)
        if not start or not end:
            continue
        x1, y1 = start
        x2, y2 = end
        parts.append(f'<line x1="{x1 + 145}" y1="{y1 + 26}" x2="{x2}" y2="{y2 + 26}" stroke="#64748B" stroke-width="2" marker-end="url(#arrow)"/>')

    parts.insert(1, '<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748B"/></marker></defs>')
    parts.append(f'<text x="32" y="{height - 24}" font-family="Arial" font-size="11" fill="#64748B">Generated by TRACE SOP Uplift</text>')
    parts.append("</svg>")
    return "".join(parts)
