import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const source = fs.readFileSync(path.resolve("client/src/pages/sop-uplift.tsx"), "utf8");

assert.match(source, /@xyflow\/react/, "SOP Uplift should use the planned ReactFlow swimlane preview dependency");
assert.match(source, /\/api\/sop-uplift\/cases/, "SOP Uplift should call the backend case API");
assert.match(source, /\/readiness/, "SOP Uplift should refresh readiness from the backend");
assert.match(source, /\/chat/, "SOP Uplift should persist case chat through the backend");
assert.match(source, /\/generate-outputs/, "SOP Uplift should trigger backend output generation");
assert.match(source, /\/upload/, "SOP Uplift should upload files into case buckets");
assert.match(source, /FormData/, "SOP Uplift uploads should use multipart form data");
assert.match(source, /type="file"/, "SOP Uplift should expose file inputs for upload buckets");
assert.match(source, /\/tag-documents/, "SOP Uplift should trigger document tagging after upload");
assert.match(source, /\/documents\/tags/, "SOP Uplift should show and refresh document tag review data");
assert.match(source, /\/run-pipeline/, "SOP Uplift should trigger the full backend pipeline");
assert.match(source, /useLlm/, "SOP Uplift should expose an LLM-mode toggle for the pipeline");
assert.match(source, /agentFollowUpQuestions/, "SOP Uplift should surface agent follow-up questions");
assert.match(source, /pipelineWarnings/, "SOP Uplift should surface pipeline warnings");
assert.match(source, /pipelineProgress/, "SOP Uplift should show pipeline progress");
assert.match(source, /source_references/, "SOP Uplift should display suggestion source references");
assert.match(source, /\/preview/, "SOP Uplift should render backend preview data");
assert.match(source, /method: "DELETE"/, "SOP Uplift should delete uploaded files through the API");
assert.match(source, /convert-to-suggestion/, "SOP Uplift should convert case chat context into suggestions");
assert.match(source, /user_text/, "SOP Uplift should submit user-edited suggestion text");
assert.match(source, /downloadOutput/, "SOP Uplift should download generated outputs");
assert.match(source, /Analyze this section/, "SOP preview should expose per-section analysis");
assert.match(source, /Continue Analysis/, "Workbench should expose resumable batch analysis");
assert.match(source, /Upload & Tag Documents/, "SOP Uplift should match the mockup workflow stepper");
assert.match(source, /Extract & Analyze/, "SOP Uplift should expose the extraction workflow step");
assert.match(source, /Review Suggestions/, "SOP Uplift should expose the review workflow step");
assert.match(source, /Generate Outputs/, "SOP Uplift should expose the outputs workflow step");
assert.match(source, /Case explorer/, "Review workspace should include the mockup case explorer rail");
assert.match(source, /Uploaded documents/, "Upload workflow should include the mockup document table");
assert.match(source, /Generated artifacts/, "Outputs workflow should include generated artifact cards");
assert.match(source, /Swimlane preview/, "Outputs workflow should include a swimlane preview");
assert.match(source, /Case chat/, "SOP Uplift should include case-scoped chat");
assert.match(source, /Case Actions/, "SOP Uplift should include the case action control from the mockup");
