import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const source = fs.readFileSync(path.resolve("client/src/pages/sop-uplift.tsx"), "utf8");
const componentDir = path.resolve("client/src/pages/sop-uplift");
const namedComponentFiles = [
  "SopUpliftHeader.tsx",
  "SopCasePanel.tsx",
  "SopUploadBuckets.tsx",
  "SopReadinessCard.tsx",
  "DocumentTagReviewTable.tsx",
  "SopPreview.tsx",
  "SuggestionQueue.tsx",
  "CaseChatPanel.tsx",
  "SwimlanePreview.tsx",
  "SopOutputPanel.tsx",
];

assert.match(source, /@xyflow\/react/, "SOP Uplift should use the planned ReactFlow swimlane preview dependency");
assert.match(source, /\/api\/sop-uplift\/cases/, "SOP Uplift should call the backend case API");
assert.match(source, /renderCaseHub/, "SOP Uplift should show a same-route case landing when no case is selected");
assert.match(source, /<HeroSection[\s\S]*title="SOP Uplift"/, "SOP Uplift should use the shared TRACE top ribbon with a stable SOP Uplift breadcrumb");
assert.match(source, /refreshCases/, "SOP Uplift should list existing SOP Uplift cases from the backend");
assert.match(source, /selectCase/, "SOP Uplift should load an existing case into the workspace");
assert.match(source, /Case portfolio/, "SOP Uplift case landing should present a richer case portfolio");
assert.match(source, /Start a case/, "SOP Uplift case landing should include a refined create-case panel");
assert.match(source, /Chat inputs captured/, "SOP Uplift case landing should include portfolio KPI status");
assert.match(source, /deleteCase/, "SOP Uplift should expose case deletion from the case hub");
assert.match(source, /Delete case/, "SOP Uplift should label the destructive case action clearly");
assert.match(source, /AlertDialog/, "Case deletion should use an in-app confirmation dialog");
assert.doesNotMatch(source, /window\.confirm/, "Case deletion should not use a browser-native confirm popup");
assert.match(source, /domain_label: caseDomain/, "Case creation should capture framework/domain context");
assert.match(source, /notes: caseNotes/, "Case creation should capture case notes");
assert.match(source, /\/readiness/, "SOP Uplift should refresh readiness from the backend");
assert.match(source, /\/chat/, "SOP Uplift should persist case chat through the backend");
assert.match(source, /context_snapshot: activeChatContext/, "Case chat should persist active workflow context with each message");
assert.match(source, /renderFloatingCaseChat/, "SOP Uplift should provide a floating case assistant across workflow pages");
assert.match(source, /TRACE case assistant/, "Floating chat should be branded as the TRACE case assistant");
assert.match(source, /setChatOpen/, "Floating chat should be minimizable and reopenable");
assert.match(source, /\/generate-outputs/, "SOP Uplift should trigger backend output generation");
assert.match(source, /\/upload/, "SOP Uplift should upload files into case buckets");
assert.match(source, /FormData/, "SOP Uplift uploads should use multipart form data");
assert.match(source, /type="file"/, "SOP Uplift should expose file inputs for upload buckets");
assert.match(source, /body\.append\("user_description"/, "SOP Uplift uploads should send optional user descriptions");
assert.match(source, /\/tag-documents/, "SOP Uplift should trigger document tagging after upload");
const uploadFunction = source.match(/const uploadFile[\s\S]*?const deleteUploadedFile/)?.[0] ?? "";
assert.doesNotMatch(uploadFunction, /await convertDocuments\(caseId\)/, "SOP Uplift should not convert uploads until extraction is run");
assert.match(source, /\/documents\/tags/, "SOP Uplift should show and refresh document tag review data");
assert.match(source, /\/run-pipeline/, "SOP Uplift should trigger the full backend pipeline");
assert.doesNotMatch(source, /\/extract/, "SOP Uplift should not call legacy frontend batch extraction endpoints");
assert.doesNotMatch(source, /\/analyze/, "SOP Uplift should not call legacy frontend batch analysis endpoints");
assert.doesNotMatch(source, /\/tasks\/analysis/, "SOP Uplift should not poll legacy analysis batch task state");
assert.match(source, /\/follow-up-questions/, "SOP Uplift should request follow-up questions without requiring a full pipeline run");
assert.match(source, /\/build-index/, "SOP Uplift should build a case-local document index");
assert.match(source, /\/index\/search/, "SOP Uplift should search only the case-local document index");
assert.match(source, /useLlm/, "SOP Uplift should expose an LLM-mode toggle for the pipeline");
assert.match(source, /use_llm: options\.forceUseLlm \?\? useLlm/, "Backend pipeline runs should honor the LLM-mode toggle");
assert.match(source, /useState\(true\)/, "AI suggestions should be enabled by default for SOP Uplift");
assert.match(source, /Proposed SOP language/, "Suggestion cards should label insert-ready text as proposed SOP language");
assert.match(source, /originLabelForSuggestion/, "Suggestion cards should show whether the recommendation came from AI, fallback rules, or the user");
assert.match(source, /\/tasks\/\$\{taskId\}/, "SOP Uplift should poll backend pipeline task state while extraction runs");
assert.match(source, /agentFollowUpQuestions/, "SOP Uplift should surface agent follow-up questions");
assert.match(source, /pipelineWarnings/, "SOP Uplift should surface pipeline warnings");
assert.match(source, /pipelineProgress/, "SOP Uplift should show pipeline progress");
assert.match(source, /source_references/, "SOP Uplift should display suggestion source references");
assert.match(source, /Open document view/, "Review pane should expose a full-screen document view");
assert.match(source, /renderOpenDocumentView/, "SOP Uplift should render the full-screen document view modal");
assert.match(source, /docx-preview/, "DOCX files should render with docx-preview");
assert.match(source, /from "xlsx"/, "Excel files should render with xlsx parsing");
assert.match(source, /react-markdown/, "Extracted review markers should render markdown instead of raw pipe-table text");
assert.match(source, /remark-gfm/, "Extracted review markers should support GitHub-flavored markdown tables");
assert.doesNotMatch(source, /activeSheet\.rows\.slice\(0,\s*250\)/, "Excel viewer should not cap sheets at 250 rows");
assert.match(source, /readWorksheetRows/, "Excel viewer should read worksheet cells from the full worksheet range");
assert.match(source, /XLSX\.utils\.decode_range/, "Excel viewer should preserve all rows and columns from the worksheet !ref");
assert.match(source, /rows x/, "Excel viewer should show row and column counts for the active sheet");
assert.match(source, /documentBuffer/, "DOCX preview should keep the loaded document buffer until the preview container is mounted");
assert.match(source, /useEffect\(\(\) => \{[\s\S]*renderAsync\(documentBuffer/, "DOCX preview should render from a mounted container, not during the fetch loading branch");
assert.doesNotMatch(source, /fallbackFile \|\| \(typeof data\.document_id === "string"/, "Supporting source labels should not be mislabeled as the selected SOP file");
assert.match(source, /cleanSourceExcerpt/, "Source reference labels should clean table markdown excerpts before display");
assert.doesNotMatch(source, /data\.excerpt\.slice\(0,\s*80\)/, "Source reference labels should not display raw table markdown excerpts");
assert.match(source, /parseMarkdownWorkbook/, "Excel viewer should fall back to converted markdown tables when raw workbook content is unavailable");
assert.match(source, /markdownDocument=\{selectedReviewDocument\}/, "Full-screen document view should pass converted document text for Excel fallbacks");
assert.match(source, /files\/\$\{file\.file_id\}\/content/, "Native viewer should fetch uploaded raw file content");
assert.match(source, /columnLabel/, "Excel viewer should render spreadsheet column letters");
assert.match(source, /cellHasComment/, "Excel viewer should highlight matched cells from review anchors");
assert.match(source, /applyDocxTextHighlights/, "DOCX viewer should apply best-effort text highlights");
assert.match(source, /trace-docx-floating-tooltip/, "DOCX native preview highlights should expose comment hover bubbles on the document page");
assert.match(source, /trace-docx-highlight/, "DOCX native preview should distinguish passive text highlights from actionable comment highlights");
assert.match(source, /applyDocxTextHighlights\(container,\s*docxHighlightMatches,\s*onSelectSuggestion\)/, "DOCX preview should attach suggestion metadata to native document highlights");
assert.match(source, /sourceLabelsForSuggestion/, "Suggestion UI should render human-readable source labels");
assert.match(source, /cleanSuggestionText/, "Suggestion UI should strip source text dumps from example language");
assert.doesNotMatch(source, /JSON\.stringify\(suggestion\.source_references/, "Suggestion UI should not render raw source reference JSON");
assert.match(source, /suggestionMatchesSelectedDocument/, "Document view should show suggestions linked through supporting source references, including Excel files");
assert.match(source, /\/preview/, "SOP Uplift should render backend preview data");
assert.match(source, /Uploaded document preview/, "Review workspace should default to a native-looking uploaded document preview");
assert.match(source, /Extracted analysis markers/, "Review workspace should keep extracted analysis markers available for best-effort highlights");
assert.match(source, /group-hover:block/, "Highlighted review text should show crisp hover bubbles for comments");
assert.match(source, /colorForSuggestion/, "Review highlights should use colour-coded suggestion states");
assert.match(source, /Repair preview/, "Review workspace should expose a reconvert action for stale or corrupt preview data");
assert.match(source, /excluding corrupt Office package text/, "Review workspace should account for binary Office preview errors");
assert.match(source, /method: "DELETE"/, "SOP Uplift should delete uploaded files through the API");
assert.match(source, /convert-to-suggestion/, "SOP Uplift should convert case chat context into suggestions");
assert.match(source, /user_text/, "SOP Uplift should submit user-edited suggestion text");
assert.match(source, /downloadOutput/, "SOP Uplift should download generated outputs");
assert.doesNotMatch(source, /Analyze this section/, "SOP preview should not expose per-section legacy analysis");
assert.doesNotMatch(source, /Continue Analysis/, "Workbench should not expose resumable legacy batch analysis");
assert.match(source, /Accept all open/, "Workbench should provide a mass accept action for open suggestions");
assert.match(source, /Rerun suggestions/, "Document viewer should let users rerun AI suggestions from the comment panel");
assert.match(source, /forceUseLlm/, "Rerun suggestions should force AI mode instead of using fallback rules");
assert.match(source, /Check LLM settings/, "Document viewer should guide users to LLM settings when fallback results indicate configuration issues");
assert.match(source, /Suggestions were generated without AI\. Rerun this analysis\./, "Case hub and review workspace should show a rerun cue for rule fallback suggestions");
assert.match(source, /caseNeedsAiRerun/, "SOP Uplift should centralize rule-fallback rerun detection for cases");
assert.match(source, /rerunCurrentCaseAnalysis/, "Review workspace should expose a general rerun analysis action");
assert.match(source, /Open document view[\s\S]*Rerun analysis/, "Review workspace document header should expose Rerun analysis through run-pipeline");
assert.match(source, /reviewProceedDialogOpen/, "Workbench should confirm output generation when suggestions remain pending");
assert.match(source, /Proceed without accepting/, "Pending suggestions dialog should not imply acceptance");
assert.match(source, /generateOutputs\(\{ allowPending: true \}\)/, "Proceeding with pending suggestions should generate outputs without accepting suggestions");
assert.match(source, /disabled=\{activeStep !== "review" \|\| !extractionComplete \|\| busy === "outputs"\}/, "Proceed to Outputs should remain disabled until the review screen is active");
assert.match(source, /Run Extraction[\s\S]*Proceed to Outputs/, "Proceed to Outputs should sit beside Run Extraction in the stage header");
assert.match(source, /Upload & Tag Documents/, "SOP Uplift should match the mockup workflow stepper");
assert.match(source, /Running extraction/, "SOP Uplift should show an in-app processing dialog while extraction runs");
assert.match(source, /refreshPipelineTask/, "Extraction should poll backend pipeline progress while the task runs");
assert.match(source, /pipelineProgress\.percent/, "Extraction progress should be driven by backend-reported percent");
assert.match(source, /\[&>button\]:hidden/, "Extraction dialog should hide the default top-right close button");
assert.match(source, /TRACE is reviewing case files\.\.\.\./, "Extraction dialog should use concise user-facing copy");
assert.doesNotMatch(source, /Minimum display time/, "Extraction dialog should not expose implementation timing details");
assert.doesNotMatch(source, /Extract & Analyze/, "SOP Uplift should not expose a redundant extraction workflow step");
assert.match(source, /Review Suggestions/, "SOP Uplift should expose the review workflow step");
assert.match(source, /Generate Outputs/, "SOP Uplift should expose the outputs workflow step");
assert.match(source, /Case explorer/, "Review workspace should include the mockup case explorer rail");
assert.match(source, /Uploaded documents/, "Upload workflow should include the mockup document table");
assert.match(source, /Generated artifacts/, "Outputs workflow should include generated artifact cards");
assert.match(source, /Swimlane preview/, "Outputs workflow should include a swimlane preview");
assert.match(source, /Case-scoped chat/, "SOP Uplift should include case-scoped chat");
assert.doesNotMatch(source, /Case Actions/, "SOP Uplift should remove the unused case action control");
assert.doesNotMatch(source, /MoreHorizontal/, "SOP Uplift should remove the unused three-dot case action button");
assert.match(source, /Extraction complete/, "Run Extraction should become a disabled completed-state control after extraction");
assert.match(source, /No uploaded documents yet/, "Upload table should show an honest empty state before real uploads");
assert.match(source, /No suggestions yet/, "Suggestion queue should show an honest empty state before analysis");
assert.match(source, /Case setup & upload/, "SOP Uplift should use the planned stage label for setup and upload");
assert.match(source, /canOpenStep/, "SOP Uplift should prevent forward navigation until prior stages are complete");
assert.match(source, /goToStep/, "SOP Uplift should centralize stage navigation gating");
assert.match(source, /setEditableStages/, "SOP Uplift should allow completed stages to be explicitly made editable");
assert.match(source, /uploadStageComplete/, "SOP Uplift should compute upload-stage completion from real uploaded and tagged SOP material");
assert.match(source, /readOnly=\{isStageReadOnly\("upload"\)\}/, "Completed upload stage should render read-only until edited");
assert.match(source, /Edit case/, "Completed stages should expose edit actions");
assert.match(source, /#005EB8/, "SOP Uplift should use latest mockup blue for primary actions and active stages");
assert.match(source, /#EAAA00/, "SOP Uplift should use amber warning/status colour tokens");
assert.match(source, /#E5001B/, "SOP Uplift should use red risk/error colour tokens");
assert.match(source, /#E8F8FD/, "SOP Uplift should use pale blue highlight colour tokens");
for (const filename of namedComponentFiles) {
  const componentSource = fs.readFileSync(path.join(componentDir, filename), "utf8");
  const componentName = path.basename(filename, ".tsx");
  assert.match(source, new RegExp(`import \\{ ${componentName} \\}`), `SOP Uplift page should import ${componentName}`);
  assert.match(source, new RegExp(`<${componentName}[\\s>]`), `SOP Uplift page should render ${componentName}`);
  assert.match(componentSource, new RegExp(`function ${componentName}|const ${componentName}`), `${filename} should define ${componentName}`);
}
assert.match(source, /type="file"[\s\S]*onChange=\{\(event\) => uploadFile\(bucket\.key, event\)\}/, "Upload bucket inputs should dispatch to uploadFile with bucket key");
assert.match(source, /documents\/\$\{tag\.file_id\}\/tags/, "Document tag review should PATCH tag overrides by file id");
assert.match(source, /disabled=\{extractionComplete \|\| !readiness\.can_analyze/, "Run extraction should be disabled after completion and gated by readiness");
assert.match(source, /aria-label="Close document view"/, "Full-screen document view should expose a visible icon close control");
assert.match(source, /Comments in this document[\s\S]*max-h-\[30vh\] shrink-0 space-y-2 overflow-y-auto/, "Document viewer should keep the comments list compact and scrollable");
assert.match(source, /Why this change/, "Document viewer selected comment should explain what changes in the SOP");
assert.match(source, /Why TRACE recommends it/, "Document viewer selected comment should explain why the suggestion is recommended");
assert.match(source, /onSelectSuggestion=\{setSelectedSuggestionId\}/, "Clicking a native document highlight should select its suggestion");
assert.doesNotMatch(source, /selectedReviewSuggestions\.slice\(0,\s*8\)/, "Document viewer should not cap the scrollable suggestion list");
assert.doesNotMatch(source, /onAnalyzeSection=\{\(anchorId\) => continueAnalysis\(\[anchorId\]\)\}/, "Preview highlights should not trigger per-section legacy analysis");
assert.match(source, /<ReactFlow nodes=\{flowNodes\} edges=\{flowEdges\}/, "Swimlane preview should render ReactFlow with generated nodes and edges");
assert.doesNotMatch(source, /starterSuggestions/, "Production SOP Uplift should not seed starter suggestions as real case data");
assert.doesNotMatch(source, /sample-1/, "Production SOP Uplift should not render sample uploads as real documents");
assert.doesNotMatch(source, /Vendor Onboarding/, "Production SOP Uplift should not hardcode vendor onboarding sample data");
assert.doesNotMatch(source, /SOP-VENDOR/, "Production SOP Uplift should not hardcode vendor output identifiers");
